<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.enjoy-iot</groupId>
        <artifactId>module-eiot-core</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>iot-script-engine</artifactId>
    <properties></properties>

    <dependencies>
        <dependency>
            <groupId>com.enjoy-iot</groupId>
            <artifactId>common</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.graalvm.sdk</groupId>
            <artifactId>graal-sdk</artifactId>
            <!--            <version>22.3.3</version>-->
            <!--            jdk8-->
            <version>19.3.6</version>
        </dependency>
        <!-- Truffle API -->
        <dependency>
            <groupId>org.graalvm.truffle</groupId>
            <artifactId>truffle-api</artifactId>
            <version>19.3.6</version>

        </dependency>
        <!-- JavaScript Language -->
        <dependency>
            <groupId>org.graalvm.js</groupId>
            <artifactId>js</artifactId>
            <version>19.3.6</version>

        </dependency>
<!--        &lt;!&ndash; Polyglot Support &ndash;&gt;-->
<!--        <dependency>-->
<!--            <groupId>org.graalvm.polyglot</groupId>-->
<!--            <artifactId>polyglot</artifactId>-->
<!--            <version>19.3.6</version>-->
<!--        </dependency>-->

    </dependencies>


</project>
